- name: check for spark installation
  become: yes
  stat:
    path: '{{spark_dir}}'
  changed_when: false
  register: spark_binary
- when: not spark_binary.stat.exists
  block:
    - name: download  spark...
      become: yes
      become_user: root
      get_url:
        url: '{{spark_url}}'
        dest: /vagrant/{{spark_archive}}
        checksum: '{{spark_checksum}}'
        mode: 0644
    - name: unarchive apache spark...
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /vagrant/{{spark_archive}}
        dest: '{{spark_parent_dir}}'
        creates: '{{spark_dir}}'
  #always:
  # - name: cleanup...
  #    become: yes
  #    become_user: root
  #    file:
  #      path: /vagrant/{{spark_archive}}
  #      state: absent
 
- name: link spark...
  become: yes
  become_user: root
  file:
    state: link
    src: '{{spark_dir}}'
    dest: '{{spark_parent_dir}}/spark' 

- name: include spark in the default path...
  become: yes
  become_user: root
  with_items:
    - f: spark.sh
      d: /etc/profile.d
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m|default("0644")}}'
    