---
spark_version: '2.4.3'
spark_checksums:    
  # https://archive.apache.org/dist/spark/spark-2.4.3/spark-2.4.3.tgz.sha512
  '2.4.3': sha512:3EAEA3B0 A81A717B B43CE6EE 0BB2C3B8 351EF080 DB9499AF 66F9F22C                  8A18D38C 5E1426CB FEF04AFD 2A4002AC E5B28A6B EACBCE4E 5E42506F                  4FD270B0 5D0DB379
spark_mirror: https://archive.apache.org
spark_parent_dir: /usr/local
 
  
